---

flink_manager_type: [taskmanager]
aws_acces_key_id: aa
aws_secret_access_key: aa

flink_env_variables:
  - "{% if flink_jemalloc_libs is defined %}LD_PRELOAD={{flink_jemalloc_libs }}{% endif %}"
  - "{% if aws_acces_key_id is defined %}AWS_ACCESS_KEY_ID={{ aws_acces_key_id }}{% endif %}"
  - "{% if aws_secret_access_key is defined %}AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}{% endif %}"